---
title: "About"
image: rc_logo_round_color.svg
about:
  template: solana
  links:
    - icon: youtube
      text: YouTube
      href: https://www.youtube.com/rconsortium
    - icon: github
      text: GitHub
      href: https://github.com/rconsortium
    - icon: twitter
      text: Twitter
      href: https://twitter.com/rconsortium
    - icon: mastodon
      text: Mastodon
      href: https://fosstodon.org/@RConsortium

---

## R Consortium Technical Blog (prototype)

The goal of the R Consortium Infrastructure Steering Committee (ISC) is to support projects that broadly help the R community. This might be software development, developing new teaching materials, documenting best practices, standardizing APIs or doing research. Currently, the ISC chiefly provides financial support for projects proposed by individuals or teams who have the skills to carry out the work. 

You can [apply to the ISC Grant Program here](https://www.r-consortium.org/all-projects/call-for-proposals). 

In this blog, we are interested in showcasing work and ideas that is help defining the direction of R. That means you! 🫵 This blog is a growing collection of voices from the R community, showing what's possible with R and where it is headed. You are not required to be a grant recipient.

If you would like to particpate, please contact the R Consortium! 
`info@r-consortium.org`